# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pr_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 501)
        MainWindow.setStyleSheet("font-family: Roboto, sans-serif;\n"
"    font-style: normal;\n"
"    font-weight: normal;\n"
"\n"
"    background:qlineargradient(spread:pad, x1:0.037, y1:0.04, x2:1, y2:1, stop:0.215789 rgba(48, 171, 171, 216), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 220, 311, 221))
        self.textEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 1px solid #356EAD;\n"
"    border-radius: 10px;\n"
"    opacity: 0.4;\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 311, 31))
        self.lineEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 1px solid #356EAD;\n"
"    border-radius: 10px;\n"
"    opacity: 0.4;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(390, 60, 361, 261))
        self.textEdit_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 1px solid #356EAD;\n"
"    border-radius: 10px;\n"
"    opacity: 0.4;\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 281, 31))
        self.label.setStyleSheet("background: none;\n"
"color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 321, 31))
        self.label_2.setStyleSheet("background: none;\n"
"color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 140, 311, 31))
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border: 1px solid #356EAD;\n"
"    border-radius: 10px;\n"
"    opacity: 0.4;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 301, 31))
        self.label_3.setStyleSheet("background: none;\n"
"color: rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 20, 281, 31))
        self.label_4.setStyleSheet("background: none;\n"
"color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        # self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        # self.progressBar.setGeometry(QtCore.QRect(400, 340, 371, 23))
        # self.progressBar.setProperty("value", 0)
        # self.progressBar.setObjectName("progressBar")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 450, 411, 16))
        self.label_5.setStyleSheet("background: none;")
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 380, 171, 51))
        self.pushButton_2.setStyleSheet("text-align: center;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"    letter-spacing: 0.04em;\n"
"    color: #FFFFFF;\n"
"    background: #5A98D0;\n"
"    box-shadow: 5px 10px 20px rgba(53, 110, 173, 0.2);\n"
"    border-radius: 10px;\n"
"    display: inline-block;\n"
"    text-decoration: none;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(400, 380, 171, 51))
        self.pushButton.setStyleSheet("text-align: center;\n"
"font:10pt \"MS Shell Dlg 2\";\n"
"    letter-spacing: 0.04em;\n"
"    color: #FFFFFF;\n"
"    background: #5A98D0;\n"
"    box-shadow: 5px 10px 20px rgba(53, 110, 173, 0.2);\n"
"    border-radius: 10px;\n"
"    display: inline-block;\n"
"    text-decoration: none;\n"
"")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\',\'sans-serif\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">(поле принимает BB-code)</span></p></body></html>"))
        self.lineEdit.setText(_translate("MainWindow", "https://"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\',\'sans-serif\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Введите адреса форумов через запятую</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Адрес вашего форума</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Адрес рекламной темы на форуме</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("MainWindow", "https://"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Шаблон рекламного сообщения</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Список форумов для рекламы</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">По вопросам поддержки обращаться к <a href=\"https://t.me/tritiumTino\"><span style=\" text-decoration: underline; color:#0000ff;\">@tritiumTino</span></a></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Начать"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
